### ISSUE TITLE
Implement the 12 ways to convert euler angles to quaternions

### ISSUE THREAD

**Issue by Paracetamol56** [Paracetamol56/Aminophenol-Game-engine#1]
Wikipedia source: https://en.wikipedia.org/wiki/Euler_angles

![](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Eulerangles.svg/300px-Eulerangles.svg.png)

**Proper Euler angles**
- z-x-z
- x-y-x
- y-z-y
- z-y-z
- x-z-x
- y-x-y

**Tait–Bryan angles**
- x-y-z
- y-z-x
- z-x-y
- x-z-y
- z-y-x
- y-x-z

**Tasks**
- [x] Euler angles enum
- [x] Euler angles to quaternions implementation
- [x] Quaternion to euler angles implementation
- [x] Euler angles rotation
